### ISSUE TITLE
Build fails on windows, cannot build eigen

### ISSUE THREAD

**Issue by eivindjahren** [equinor/GraphSPME#59]
https://github.com/equinor/GraphSPME/actions/runs/8293096420/job/22695564889

**Comment by andreas-el** [comment]
Seems like there is some missing definitions for some intrinsics, possibly change in Eigen or a runner update.
Tried pinning Eigen to 3.4.0, but that did not resolve the issue.
Discussed with @Blunde1 and decided on building only 64-bit wheels.
